apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "food-delivery.fullname" . }}
  labels:
    {{- include "food-delivery.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      {{- include "food-delivery.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "food-delivery.selectorLabels" . | nindent 8 }}

    spec:
      containers:
        - name: food-delivery-container

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

          env:
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.database.url | quote }}

            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.database.username | quote }}

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: food-delivery-db-secret
                  key: SPRING_DATASOURCE_PASSWORD
